### ISSUE TITLE
[BUG] Step doesn't fail after throwing `Unhandled rejection Error`

### ISSUE THREAD

**Issue by VillagerTom** [xireiki/channel-post#3]
See:
https://github.com/VillagerTom/test_action/actions/runs/7987267963/job/21809394187
https://github.com/VillagerTom/test_action/actions/runs/7972799197/job/21765304070

**Comment by xireiki** [comment]
Should have been fixed

**Comment by xireiki** [comment]
Please note that due to Telegram official restrictions, it is not possible to send files with a total size of more than 50M

**Comment by VillagerTom** [comment]
Will this action be able to send large files in the future, by hosting a local telegram bot api server in the GitHub machine?

**Comment by xireiki** [comment]
This is feasible.

**Comment by VillagerTom** [comment]
静候佳音。

**Comment by xireiki** [comment]
@VillagerTom 完成了，但是不支持非 x86_64 架构，以及非 Linux、MacOS 和 Windows
