### ISSUE TITLE
[Bug] `parse_mode: Markdown(V2)`  seems not work.

### ISSUE THREAD

**Issue by VillagerTom** [xireiki/channel-post#4]
![Screenshot_2024-02-23-22-20-05-06](https://github.com/xireiki/channel-post/assets/89803422/4f5f5d5d-7f76-45d8-ad9b-24b09502cbe5)
![Screenshot_2024-02-23-22-12-43-05](https://github.com/xireiki/channel-post/assets/89803422/7e9f4fd0-a341-4032-8ab3-090c3298b76f)

**Comment by xireiki** [comment]
模式解析不是由我完成的，我只是传递了参数，具体请自行查看 [Telegram Bot Api 文档](https://core.telegram.org/bots/api#markdownv2-style) 测试

**Comment by VillagerTom** [comment]
噢原来它的Markdown语法与通用的语法不一样😂
```
*这是粗体*
_这是斜体_
__这是下划线__
~这是删除线~
||这是马赛克||
```
等宽字体和代码块语法倒是一样。
我觉得有必要在readme里说明一下。（贴一个链接就行）

**Comment by xireiki** [comment]
@VillagerTom 这个可以👌

**Comment by VillagerTom** [comment]
这似乎不是markdown v2与v1的区别，你看文档下面的“Markdown style”段落，它也跟常规语法不一样。

**Comment by VillagerTom** [comment]
另外你的示例里还是用的常规语法

**Comment by VillagerTom** [comment]
README里的`bot_api`是不是应该改成`bot_token`？
